### ISSUE TITLE
[CircleCI] Module not found, build failing

### ISSUE THREAD

**Issue by polcham** [creativetimofficial/material-kit-react#41]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The CircleCI build will successfully build without Module not found error.

# Current Behavior

The CircleCI build is failing with a Module not found error.

## Steps to Reproduce

1. Unzip, material-kit-react-v1.2.0.zip, call npm install.
2. Copy entire directory to repository.
3. npm install
4. npm install --g cross-env
5. Added NODE_PATH=./src in package.json scripts, alternatively can create .env file with NODE_PATH=src.
6. Commit and push repository.  

## Context

Added NODE_PATH=./src in package.json scripts, even tried with creating .env file with NODE_PATH=src, both method works locally, but the committed repository on CircleCI is always failing. I even tried making absolute path to relative path, still no luck. Tried all variations of NODE_PATH=./src everything works locally, but not on CircleCI. Even tried setting environment on config.yml.

config.yml
```
- run:
  name: (Production) Build
  command: npm run build
  environment:
    NODE_PATH: src/
```

package.json
```
"scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint:check": "eslint . --ext=js,jsx;  exit 0",
    "lint:fix": "eslint . --ext=js,jsx --fix;  exit 0",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start",
    "build-package-css": "node-sass-chokidar src/assets/scss/material-kit-react.scss dist/material-kit-react.css",
    "build-package": "npm run build-package-css && babel src --out-dir dist"
},
```
config.yml
```
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12.0
      - image: fstab/aws-cli

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get -y -qq install awscli
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: aws configure set default.s3.signature_version s3v4
      - run: aws s3 cp ./build s3://admin.app.com/ --recursive --region eu-west-2
```
* npm: 6.4.1
* node: v8.12.0

## Failure Logs

.env with NODE_PATH=src, local npm run build, builds successfully.
```
> material-kit-react@1.2.0 build /home/circleci/repo
> npm run build-css && react-scripts build


> material-kit-react@1.2.0 build-css /home/circleci/repo
> node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/

Wrote 1 CSS files to /home/circleci/repo/src/
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'views/Components/Components.jsx' in '/home/circleci/repo/src/routes'


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-kit-react@1.2.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-kit-react@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-09-20T13_53_00_276Z-debug.log
Exited with code 1
```
